### ISSUE TITLE
How to use this lib

### ISSUE THREAD

**Issue by ThreeMinutesFix** [Harshshah6/YT_VIDEO_UTIL#2]
I have read the doc but want to use it in exoplayer can you help

**Comment by Harshshah6** [comment]
bro this can be implemented in java,kotlin,
for implementing in exoplayer first the the download urls into an string and just make your player to play from that download url , the video will be loaded and also can be played because its the direct link of the video 👍

**Comment by ThreeMinutesFix** [comment]
yeah brother i tried 
`util_name.ReqListener(new LegendaryListener(){
		    @Override
		    public void onSuccess(String _mssg){

                                 //on getting success / all onSuccess Event codes must me placed here
			    }
		
		public void onFail(String _mssg){
				//OnError
                                //_mssg <- returns the error message                              
		}
});`

but dont know how to extract urls can you guide me on that code if possible

**Comment by Harshshah6** [comment]
ArrayList<HashMap<String,Object>> links =  LegendaryUtil.getMP4();
String url1 = links.get(0).get("link");
//url1  is your video link

/* key :-
1. link
2. size
*/

**Comment by ThreeMinutesFix** [comment]
what i did is 
  util_name = new LegendaryUtil(context);
        util_name.setVideoUri(trailerUrl);
  util_name.ReqListener(new LegendaryListener(){
            @Override
            public void onSuccess(String _mssg){

                ArrayList<HashMap<String, Object>> links = LegendaryUtil.getMP4();
                if (!links.isEmpty()) {
                    String url1 = (String) links.get(0).get("link");
                    Toast.makeText(context, "" + url1, Toast.LENGTH_SHORT).show();
                } else {
                    Toast.makeText(context, "eeee", Toast.LENGTH_SHORT).show();
                }

            }

            public void onFail(String _mssg){
                //OnError
                //_mssg <- returns the error message
            }
but it returning empty url may be i am doing something wrong ?  my guess is url is not passing in but according to [doc](https://github.com/Harshshah6/YT_VIDEO_UTIL/blob/master/Documentation/Usage.md) i used util_name.setVideoUri("video_url_here"); and declared globally

**Comment by Harshshah6** [comment]
it might be api (rapidapi) response error or there might be some error :/

there's nothing wrong in the code you gave everything's fine 🤔

**Comment by Harshshah6** [comment]
Ok, I'll check it out.
